apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: client                       # add the correct container registry URL as a prefix infront of "client"
        imagePullPolicy: IfNotPresent
        env:
        - name: REACT_APP_SERVERURL
          value: http://localhost:5000      # change 'localhost' to the server's public IP
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000