apiVersion: v1
kind: Pod
metadata:
  name: over-node-cpu-limit
spec:
  restartPolicy: Always
  containers:
  - name: over-node-cpu-limit
    image: vish/stress
    resources:
      requests:
        cpu: 100000m
        memory: 100Mi
      limits:
        cpu: 100000m
        memory: 200Mi
    args: ["-cpus", "2"]