apiVersion: v1
kind: Pod
metadata:
  name: within-node-cpu-limit
spec:
  restartPolicy: Always
  containers:
  - name: within-node-cpu-limit
    image: vish/stress
    resources:
      requests:
        cpu: 15m
        memory: 100Mi
      limits:
        cpu: 30m
        memory: 200Mi
    args: ["-cpus", "2"]