apiVersion: v1
kind: Pod
metadata:
  name: within-container-memory-limit
spec:
  restartPolicy: Always
  containers:
  - name: within-container-memory-limit
    image: polinux/stress
    resources:
      requests:
        cpu: 15m
        memory: 100Mi
      limits:
        cpu: 30m
        memory: 200Mi
    command: [stress]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]